exports.BattleFormats = {
	oldschoolclause: {
		effectType: 'Rule',
		onStart: function () {
			this.add('rule', 'Old School Clause: Only Hidden Power and moves introduced in the first generation are allowed.');
		},
		validateSet: function(set) {
			var issues = [];
			var allowedMoves = [
				'Absorb',
				'Acid',
				'Acid Armor',
				'Agility',
				'Amnesia',
				'Aurora Beam',
				'Barrage',
				'Barrier',
				'Bide',
				'Bind',
				'Bite',
				'Blizzard',
				'Body Slam',
				'Bone Club',
				'Bonemerang',
				'Bubble',
				'Bubble Beam',
				'Clamp',
				'Comet Punch',
				'Confuse Ray',
				'Confusion',
				'Constrict',
				'Conversion',
				'Counter',
				'Crabhammer',
				'Cut',
				'Defense Curl',
				'Dig',
				'Disable',
				'Dizzy Punch',
				'Double-Edge',
				'Double Kick',
				'Double Slap',
				'Double Team',
				'Dragon Rage',
				'Dream Eater',
				'Drill Peck',
				'Earthquake',
				'Egg Bomb',
				'Ember',
				'Explosion',
				'Fire Blast',
				'Fire Punch',
				'Fire Spin',
				'Fissure',
				'Flamethrower',
				'Flash',
				'Fly',
				'Focus Energy',
				'Fury Attack',
				'Fury Swipes',
				'Glare',
				'Growl',
				'Growth',
				'Guillotine',
				'Gust',
				'Harden',
				'Haze',
				'Headbutt',
				'High Jump Kick',
				'Horn Attack',
				'Horn Drill',
				'Hydro Pump',
				'Hyper Beam',
				'Hyper Fang',
				'Hypnosis',
				'Ice Beam',
				'Ice Punch',
				'Jump Kick',
				'Karate Chop',
				'Kinesis',
				'Leech Life',
				'Leech Seed',
				'Leer',
				'Lick',
				'Light Screen',
				'Lovely Kiss',
				'Low Kick',
				'Meditate',
				'Mega Drain',
				'Mega Kick',
				'Mega Punch',
				'Metronome',
				'Mimic',
				'Minimize',
				'Mirror Move',
				'Mist',
				'Night Shade',
				'Pay Day',
				'Peck',
				'Petal Dance',
				'Pin Missile',
				'Poison Gas',
				'Poison Powder',
				'Poison Sting',
				'Pound',
				'Psybeam',
				'Psychic',
				'Psywave',
				'Quick Attack',
				'Rage',
				'Razor Leaf',
				'Razor Wind',
				'Recover',
				'Reflect',
				'Rest',
				'Roar',
				'Rock Slide',
				'Rock Throw',
				'Rolling Kick',
				'Sand Attack',
				'Scratch',
				'Screech',
				'Seismic Toss',
				'Self-Destruct',
				'Sharpen',
				'Sing',
				'Skull Bash',
				'Sky Attack',
				'Slam',
				'Slash',
				'Sleep Powder',
				'Sludge',
				'Smog',
				'Smokescreen',
				'Soft-Boiled',
				'Solar Beam',
				'Sonic Boom',
				'Spike Cannon',
				'Splash',
				'Spore',
				'Stomp',
				'Strength',
				'String Shot',
				'Struggle',
				'Stun Spore',
				'Submission',
				'Substitute',
				'Super Fang',
				'Supersonic',
				'Surf',
				'Swift',
				'Swords Dance',
				'Tackle',
				'Tail Whip',
				'Take Down',
				'Teleport',
				'Thrash',
				'Thunder',
				'Thunderbolt',
				'Thunder Punch',
				'Thunder Shock',
				'Thunder Wave',
				'Toxic',
				'Transform',
				'Tri Attack',
				'Twineedle',
				'Vice Grip',
				'Vine Whip',
				'Waterfall',
				'Water Gun',
				'Whirlwind',
				'Wing Attack',
				'Withdraw',
				'Wrap',
				'Hidden Power'
			].map(function(x){return toId(x);});
			var movesLength = set.moves.length;
			var movedex = require('./moves.js').BattleMovedex;
			for (i = 0; i < movesLength; i++) {
				var move = movedex[toId(set.moves[i])];
				var id = move.id;
				if (allowedMoves.indexOf(id) === -1) {
					issues.push(set.species + "'s " + move.name + " is not allowed.");
				}
			}
			return issues;
		}
	}
}